import { StyleSheet } from "react-native";

export const CarritoEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#f9fafb" },
  encabezado: {
    padding: 20,
    paddingTop: 60,
    backgroundColor: "#fff",
    alignItems: "center",
  },
  titulo: { fontSize: 20, fontWeight: "bold", color: "#1f2937" },
  lista: { padding: 20 },
  item: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
  },
  itemInfo: { flexDirection: "row", alignItems: "center" },
  cantidadBadge: {
    backgroundColor: "#eee",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
    marginRight: 10,
  },
  itemNombre: { fontSize: 16, fontWeight: "600", color: "#374151" },
  itemDetalles: { marginTop: 4 },
  textoExtra: { fontSize: 12, color: "#6b7280" },
  textoInstruccion: {
    fontSize: 12,
    color: "#C21833",
    fontStyle: "italic",
    marginTop: 2,
  },
  itemPrecio: { fontSize: 16, fontWeight: "bold", color: "#374151" },
  resumen: { backgroundColor: "#fff", padding: 20, marginTop: 20 },
  filaResumen: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  textoResumen: { fontSize: 16, color: "#6b7280" },
  textoTotal: { fontSize: 18, fontWeight: "bold", color: "#1f2937" },
  botonPagar: {
    backgroundColor: "#C21833",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
  },
  textoBoton: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  botonToggle: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    marginHorizontal: 2,
    borderRadius: 8,
    gap: 8,
  },
  botonToggleActivo: {
    backgroundColor: "#fff1f2",
    borderColor: "#e11d48",
  },
  textoToggle: {
    fontSize: 14,
    color: "#64748b",
    fontWeight: "600",
  },
  textoToggleActivo: {
    color: "#e11d48",
  },
  tituloSeccion: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 10,
  },
  filaDetalle: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 8,
    marginBottom: 10,
  },
  textoEtiqueta: { fontSize: 12, color: "#6b7280" },
  textoValor: { fontSize: 14, fontWeight: "600", color: "#374151" },
  botonMetodoPago: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 8,
  },
  botonMetodoPagoActivo: {
    borderColor: "#C21833",
    backgroundColor: "#fff5f5",
  },
  textoMetodoPago: { fontSize: 14, color: "#6b7280", fontWeight: "600" },
  textoMetodoPagoActivo: { color: "#C21833" },
  inputNotas: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    height: 80,
    textAlignVertical: "top",
    color: "#374151",
  },
});
