import { StyleSheet } from "react-native";

export const DashboardEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#fff0f0" },
  encabezado: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
  },
  saludo: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  subtitulo: { fontSize: 16, color: "rgba(255,255,255,0.8)" },
  botonNotificacion: {
    padding: 10,
    backgroundColor: "#fff",
    borderRadius: 50,
  },
  contenedorEstadisticas: {
    flexDirection: "row",
    paddingHorizontal: 20,
    gap: 15,
    marginBottom: 25,
  },
  tarjeta: {
    flex: 1,
    padding: 20,
    borderRadius: 24,
    justifyContent: "space-between",
    height: 130,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  valorTarjeta: {
    fontSize: 28, // Adjusted for balance
    fontWeight: "800",
    color: "#fff",
    marginTop: 10,
  },
  etiquetaTarjeta: {
    fontSize: 13,
    color: "rgba(255,255,255,0.9)",
    fontWeight: "600",
  },
  tituloSeccion: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1f2937",
    marginLeft: 20,
    marginBottom: 20,
    letterSpacing: -0.5,
  },
  cuadricula: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    marginBottom: 30, // More space
  },
  elementoCuadricula: { width: "25%", alignItems: "center", marginBottom: 15 },
  contenedorIcono: {
    width: 65,
    height: 65,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  etiquetaCuadricula: { fontSize: 12, color: "#4b5563", fontWeight: "500" },
  lista: { paddingHorizontal: 20, paddingBottom: 40 },
  elementoLista: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  textoLista: { flex: 1, marginLeft: 15, fontSize: 14, color: "#374151" },
  tiempoLista: { fontSize: 12, color: "#9ca3af" },
});
