import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const LoginEstilos = StyleSheet.create({
  fondo: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 40,
  },
  logoImagen: {
    width: 120,
    height: 120,
    resizeMode: "contain",
    marginBottom: 20,
    borderRadius: 15,
  },
  titulo: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 5,
  },
  subtitulo: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    textAlign: "center",
    paddingHorizontal: 40,
  },
  tarjeta: {
    width: width * 0.9,
    backgroundColor: "#fff",
    borderRadius: 32,
    padding: 35,
    alignItems: "center",
    shadowColor: "#C21833",
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  tarjetaTitulo: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 8,
  },
  tarjetaSubtitulo: {
    fontSize: 15,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 35,
    lineHeight: 22,
  },
  inputContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f3f4f6",
    borderRadius: 16,
    paddingHorizontal: 20,
    height: 60,
    marginBottom: 25,
    backgroundColor: "#f9fafb",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  inputIcono: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: "#374151",
  },
  labelPin: {
    fontSize: 14,
    color: "#4b5563",
    marginBottom: 15,
    fontWeight: "500",
  },
  pinContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    marginBottom: 30,
    width: "100%",
  },
  pinInput: {
    width: 50,
    height: 50,
    borderWidth: 1.5,
    borderColor: "#C21833",
    borderRadius: 12,
    textAlign: "center",
    fontSize: 24,
    fontWeight: "bold",
    color: "#C21833",
    backgroundColor: "#fff0f0",
  },
  botonIngresar: {
    width: "100%",
    backgroundColor: "#C21833",
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#C21833",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  textoBoton: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  footerNota: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    padding: 10,
    borderRadius: 8,
    width: "100%",
  },
  textoNota: {
    fontSize: 12,
    color: "#6b7280",
    marginLeft: 10,
    flex: 1,
  },
});
