import { StyleSheet } from "react-native";

export const PerfilEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#f4f4f5" },
  encabezado: {
    backgroundColor: "#fff",
    paddingTop: 60,
    alignItems: "center",
    paddingVertical: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 5,
    marginBottom: 20,
    zIndex: 1,
  },
  contenedorAvatar: { marginBottom: 10 },
  nombre: { fontSize: 24, fontWeight: "bold", color: "#333" },
  correo: { fontSize: 14, color: "#888", marginBottom: 10 },
  seccion: {
    backgroundColor: "#fff",
    marginHorizontal: 15,
    paddingHorizontal: 20,
    borderRadius: 24,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  tituloSeccion: {
    fontSize: 14,
    fontWeight: "600",
    color: "#888",
    marginTop: 15,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  fila: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  filaIzquierda: { flexDirection: "row", alignItems: "center" },
  icono: { width: 30, marginRight: 10, textAlign: "center" },
  textoFila: { fontSize: 16, color: "#333" },
  botonCerrarSesion: {
    marginTop: 30,
    marginHorizontal: 20,
    backgroundColor: "#fff",
    padding: 18,
    borderRadius: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ff4d4d",
  },
  textoCerrarSesion: { color: "#ff4d4d", fontWeight: "bold", fontSize: 16 },
});
