import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const ProductoEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#fff" },
  scrollContent: { paddingBottom: 100 },
  headerImagen: { position: "relative" },
  imagen: { width: width, height: 300, resizeMode: "cover" },
  botonAtras: {
    position: "absolute",
    top: 50,
    left: 20,
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 10,
    borderRadius: 25,
    zIndex: 10,
  },
  botonFavorito: {
    position: "absolute",
    top: 50,
    right: 20,
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 10,
    borderRadius: 25,
    zIndex: 10,
  },
  infoContenedor: { flex: 1, padding: 20 },
  encabezadoInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  nombre: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#1f2937",
    flex: 1,
    marginRight: 10,
  },
  precio: { fontSize: 24, fontWeight: "800", color: "#C21833" },
  metaInfo: { flexDirection: "row", gap: 15, marginBottom: 15 },
  etiquetaMeta: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    gap: 5,
  },
  textoMeta: { fontSize: 13, color: "#4b5563", fontWeight: "600" },
  descripcion: {
    fontSize: 16,
    color: "#6b7280",
    lineHeight: 24,
    marginBottom: 25,
  },
  tituloSeccion: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 15,
    marginTop: 10,
  },
  extraItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  extraInfo: { flexDirection: "row", alignItems: "center", gap: 12 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#d1d5db",
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxSeleccionado: {
    backgroundColor: "#C21833",
    borderColor: "#C21833",
  },
  nombreExtra: { fontSize: 16, color: "#374151" },
  precioExtra: { fontSize: 15, color: "#6b7280", fontWeight: "500" },
  inputInstrucciones: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 15,
    fontSize: 15,
    color: "#1f2937",
    height: 100,
    textAlignVertical: "top",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#f3f4f6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -5 },
    elevation: 10,
  },
  controlCantidad: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f3f4f6",
    borderRadius: 30, // Pill shape
    padding: 5,
  },
  botonCantidad: {
    width: 35,
    height: 35,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 17.5,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 2,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  textoCantidad: { fontSize: 18, fontWeight: "bold", paddingHorizontal: 15 },
  botonAgregar: {
    backgroundColor: "#C21833",
    paddingVertical: 16,
    paddingHorizontal: 25,
    borderRadius: 16,
    flex: 1,
    marginLeft: 15,
    flexDirection: "row",
    justifyContent: "center",
  },
  textoBoton: { color: "#fff", fontWeight: "bold", fontSize: 16 },
});
