ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS password VARCHAR(255) DEFAULT '123456';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS rol VARCHAR(50) DEFAULT 'cliente';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS avatar VARCHAR(50) DEFAULT 'user';
